Pass DWORD handles through the PtrToUlong macro.
Some legacy win32 interfaces expect resource handles in data types that
are too narrow for 64-bit systems.  GCC 5 returns an error when these
handles are casted, even when the permissive flag is used.

NB:

  * https://msdn.microsoft.com/en-us/library/windows/desktop/aa384242.aspx

Resolves:

	In file included from midi.cpp:141:0:
	midi_win32.h: In member function ‘virtual bool MidiHandler_win32::Open(const char*)’:
	midi_win32.h:115:47: error: cast from ‘HANDLE {aka void*}’ to ‘DWORD {aka long unsigned int}’ loses precision [-fpermissive]
	res = midiOutOpen(&m_out, nummer, (DWORD)m_event, 0, CALLBACK_EVENT);