Cast the GetSetSDLValue result into a wide pointer.
GetSetSDLValue returns void*, which is wider than a regular integer on
64-bit platforms.

Use uintptr_t from stddef.h instead, which should be the same size as
void* and implemented by all toolchains.

Resolves:

	menu.cpp:977:85: error: cast from ‘void*’ to ‘int’ loses precision [-fpermissive]
	  CheckMenuItem(m_handle, ID_SURFACE, ((int) GetSetSDLValue(1, "desktop.want_type", 0) == SCREEN_SURFACE) ? MF_CHECKED : MF_STRING);