Fully qualify isinf in MinGW builds.
Call std::isinf explicitly instead of adjusting the namespace.

Resolves:

	fpu_instructions.h: In function ‘void FPU_FCOM(Bitu, Bitu)’:
	fpu_instructions.h:457:27: error: ‘isinf’ was not declared in this scope
	   if (isinf(fpu.regs[st].d) && isinf(fpu.regs[other].d)) {