src/gui/render.cpp: Add missing ifdef conditional on C_METAL
Fixes this build error when building without Metal support on macOS/Darwin:

    render.cpp:891:37: error: use of undeclared identifier 'SCREEN_METAL'
      891 |             && (sdl.desktop.type != SCREEN_METAL)
          |                                     ^~~~~~~~~~~~
    render.cpp:1379:36: error: use of undeclared identifier 'SCREEN_METAL'
     1379 |             if(sdl.desktop.type == SCREEN_METAL) return false;
          |                                    ^~~~~~~~~~~~
    2 errors generated.
    make[3]: *** [render.o] Error 1

Fixes: 6a30e3c ("METAL: Consider existence of Metal support on build")
Signed-off-by: Daniel Scheller <d.scheller@gmx.net>