configure.ac: Fix error in setpriority test
On some compilers this error would happen:

> conftest.c:39:5: error: second parameter of 'main' (argument array) must be of type 'char **'
> int main(int argc,char * argv) {
>     ^

This is absurd because the test clearly has argv[] in it, but it's
getting dropped for some reason. Just avoid this by writing char**