Use posix time interfaces in MinGW builds.
MinGW implements things like sys/time.h and gettimeofday.

GCC 5 requires explicit casting from tv_sec into time_t.

Resolves:

	cmos.cpp:44:8: error: redefinition of ‘struct timeval’
	 struct timeval {

	In file included from /usr/x86_64-w64-mingw32/sys-root/mingw/include/time.h:255:0,
	                 from cmos.cpp:20:
	/usr/x86_64-w64-mingw32/sys-root/mingw/include/_timeval.h:10:8: error: previous definition of ‘struct timeval’
	 struct timeval

	cmos.cpp:139:45: error: cannot convert ‘long int*’ to ‘const time_t* {aka const long long int*}’ for argument ‘1’ to ‘tm* localtime(const time_t*)’
	    loctime = localtime(&cmos.locktime.tv_sec);

	cmos.cpp:144:31: error: ‘gettimeofday’ was not declared in this scope
	    gettimeofday(&curtime, NULL);